LOCAL_DIR := $(GET_LOCAL_DIR)

MODULE := $(LOCAL_DIR)
TOOLCHAIN_PREFIX := powerpc64-unknown-linux-gnuabielfv2-
ARCH_COMPILEFLAGS += -mcpu=powerpc -m32 -static-libgcc -lgcc
ARCH_LDFLAGS += -melf32ppc

MODULE_SRCS += $(LOCAL_DIR)/boot.S $(LOCAL_DIR)/arch.c $(LOCAL_DIR)/thread.c $(LOCAL_DIR)/timer.c

MODULE_SRCS += $(LOCAL_DIR)/mmu.c

GLOBAL_DEFINES += PLATFORM_HAS_DYNAMIC_TIMER=1 ARCH_HAS_MMU=1 IS_64BIT=1

ARCH_OPTFLAGS := -O1

ifeq (true,$(call TOBOOL,$(WITH_KERNEL_VM)))
  KERNEL_ASPACE_BASE := 0x1000000
  KERNEL_ASPACE_SIZE := 0x1000000

  GLOBAL_DEFINES += ARCH_HAS_MMU=1 KERNEL_ASPACE_BASE=$(KERNEL_ASPACE_BASE) KERNEL_ASPACE_SIZE=$(KERNEL_ASPACE_SIZE)
endif

include make/module.mk
